"""about_user column added to user table

Revision ID: 77860d1f6d71
Revises: 8a1bb6fe5d83
Create Date: 2021-11-21 10:54:45.471690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77860d1f6d71'
down_revision = '8a1bb6fe5d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_user')
    # ### end Alembic commands ###
